#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : OpenCSG
Version  : 1.4.2
Release  : 1
URL      : http://www.opencsg.org/OpenCSG-1.4.2.tar.gz
Source0  : http://www.opencsg.org/OpenCSG-1.4.2.tar.gz
Summary  : The OpenGL Extension Wrangler library
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0
Requires: OpenCSG-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-qmake
BuildRequires : freeglut-dev
BuildRequires : glew-dev
BuildRequires : glu-dev

%description
# GLEW - The OpenGL Extension Wrangler Library
http://glew.sourceforge.net/
https://github.com/nigels-com/glew

%package license
Summary: license components for the OpenCSG package.
Group: Default

%description license
license components for the OpenCSG package.


%prep
%setup -q -n OpenCSG-1.4.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
%qmake
test -r config.log && cat config.log
make

%install
export SOURCE_DATE_EPOCH=1546371751
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/OpenCSG
cp glew/LICENSE.txt %{buildroot}/usr/share/package-licenses/OpenCSG/glew_LICENSE.txt
cp glew/doc/gpl.txt %{buildroot}/usr/share/package-licenses/OpenCSG/glew_doc_gpl.txt
cp license.txt %{buildroot}/usr/share/package-licenses/OpenCSG/license.txt
%make_install

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/OpenCSG/glew_LICENSE.txt
/usr/share/package-licenses/OpenCSG/glew_doc_gpl.txt
/usr/share/package-licenses/OpenCSG/license.txt
