#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : OpenCSG
Version  : 1.4.2
Release  : 7
URL      : http://www.opencsg.org/OpenCSG-1.4.2.tar.gz
Source0  : http://www.opencsg.org/OpenCSG-1.4.2.tar.gz
Summary  : The OpenGL Extension Wrangler library
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0
Requires: OpenCSG-lib = %{version}-%{release}
Requires: OpenCSG-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-qmake
BuildRequires : freeglut-dev
BuildRequires : glew-dev
BuildRequires : glu-dev
Patch1: build.patch

%description
# GLEW - The OpenGL Extension Wrangler Library
![](http://glew.sourceforge.net/glew.png)

%package dev
Summary: dev components for the OpenCSG package.
Group: Development
Requires: OpenCSG-lib = %{version}-%{release}
Provides: OpenCSG-devel = %{version}-%{release}
Requires: OpenCSG = %{version}-%{release}

%description dev
dev components for the OpenCSG package.


%package lib
Summary: lib components for the OpenCSG package.
Group: Libraries
Requires: OpenCSG-license = %{version}-%{release}

%description lib
lib components for the OpenCSG package.


%package license
Summary: license components for the OpenCSG package.
Group: Default

%description license
license components for the OpenCSG package.


%prep
%setup -q -n OpenCSG-1.4.2
cd %{_builddir}/OpenCSG-1.4.2
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export GCC_IGNORE_WERROR=1
%qmake QMAKE_CFLAGS+=-fno-lto QMAKE_CXXFLAGS+=-fno-lto  INSTALLDIR=/usr
test -r config.log && cat config.log
make

%install
export SOURCE_DATE_EPOCH=1604606020
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/OpenCSG
cp %{_builddir}/OpenCSG-1.4.2/glew/LICENSE.txt %{buildroot}/usr/share/package-licenses/OpenCSG/0ca22faedb8ee495473a82c4d91452493b22ac9f
cp %{_builddir}/OpenCSG-1.4.2/glew/doc/gpl.txt %{buildroot}/usr/share/package-licenses/OpenCSG/4d1d37f306ed270cda5b2741fac3abf0a7b012e5
cp %{_builddir}/OpenCSG-1.4.2/license.txt %{buildroot}/usr/share/package-licenses/OpenCSG/71c792dea8e57d7859f61cfef5f735f41d39e40c
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/opencsg.h
/usr/lib64/libopencsg.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libopencsg.so.1
/usr/lib64/libopencsg.so.1.4
/usr/lib64/libopencsg.so.1.4.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/OpenCSG/0ca22faedb8ee495473a82c4d91452493b22ac9f
/usr/share/package-licenses/OpenCSG/4d1d37f306ed270cda5b2741fac3abf0a7b012e5
/usr/share/package-licenses/OpenCSG/71c792dea8e57d7859f61cfef5f735f41d39e40c
